export const DELETE_PATH_REDUCER = 'DELETE_PATH_REDUCER';
export const ADD_PATH_REDUCER = 'ADD_PATH_REDUCER';
export const SET_IS_NEW_PATH = 'SET_IS_NEW_PATH';
export const INFO_PATH_REDUCER = 'INFO_PATH_REDUCER';
export const CHECK_ERROR_PATH = 'CHECK_ERROR_PATH';
export const SAVE_UPDATE_DATA = 'SAVE_UPDATE_DATA';

export const INFO_CAR_TO_NAME = 'INFO_CAR_TO_NAME';
export const DELETE_CAR_TO_NAME = 'DELETE_CAR_TO_NAME';
export const SET_IS_NEW_CAR = 'SET_IS_NEW_CAR';
export const SAVE_CAR = 'SAVE_CAR';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';
export const LOAD_LOCAL_STORAGE = 'LOAD_LOCAL_STORAGE';
export const INIT_LOAD_LOCAL_STORAGE = 'INIT_LOAD_LOCAL_STORAGE';
export const SAVE_LOCAL_STORAGE = 'SAVE_LOCAL_STORAGE';

export const SAVE_LOCALSTORAGE_BEGIN = 'SAVE_LOCALSTORAGE_BEGIN';
export const SAVE_LOCALSTORAGE_SUCCESSED = 'SAVE_LOCALSTORAGE_SUCCESSED';
export const SAVE_LOCALSTORAGE_FAILED = 'SAVE_LOCALSTORAGE_FAILED';
